// Code generated by counterfeiter. DO NOT EDIT.
package goasyncfakes

import (
	"context"
	"sync"

	"github.com/DanLavine/goasync"
)

type FakeTaskManager struct {
	AddRunningTaskStub        func(string, goasync.RunningTask) error
	addRunningTaskMutex       sync.RWMutex
	addRunningTaskArgsForCall []struct {
		arg1 string
		arg2 goasync.RunningTask
	}
	addRunningTaskReturns struct {
		result1 error
	}
	addRunningTaskReturnsOnCall map[int]struct {
		result1 error
	}
	AddTaskStub        func(string, goasync.Task) error
	addTaskMutex       sync.RWMutex
	addTaskArgsForCall []struct {
		arg1 string
		arg2 goasync.Task
	}
	addTaskReturns struct {
		result1 error
	}
	addTaskReturnsOnCall map[int]struct {
		result1 error
	}
	RunStub        func(context.Context) []goasync.NamedError
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 []goasync.NamedError
	}
	runReturnsOnCall map[int]struct {
		result1 []goasync.NamedError
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskManager) AddRunningTask(arg1 string, arg2 goasync.RunningTask) error {
	fake.addRunningTaskMutex.Lock()
	ret, specificReturn := fake.addRunningTaskReturnsOnCall[len(fake.addRunningTaskArgsForCall)]
	fake.addRunningTaskArgsForCall = append(fake.addRunningTaskArgsForCall, struct {
		arg1 string
		arg2 goasync.RunningTask
	}{arg1, arg2})
	stub := fake.AddRunningTaskStub
	fakeReturns := fake.addRunningTaskReturns
	fake.recordInvocation("AddRunningTask", []interface{}{arg1, arg2})
	fake.addRunningTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskManager) AddRunningTaskCallCount() int {
	fake.addRunningTaskMutex.RLock()
	defer fake.addRunningTaskMutex.RUnlock()
	return len(fake.addRunningTaskArgsForCall)
}

func (fake *FakeTaskManager) AddRunningTaskCalls(stub func(string, goasync.RunningTask) error) {
	fake.addRunningTaskMutex.Lock()
	defer fake.addRunningTaskMutex.Unlock()
	fake.AddRunningTaskStub = stub
}

func (fake *FakeTaskManager) AddRunningTaskArgsForCall(i int) (string, goasync.RunningTask) {
	fake.addRunningTaskMutex.RLock()
	defer fake.addRunningTaskMutex.RUnlock()
	argsForCall := fake.addRunningTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskManager) AddRunningTaskReturns(result1 error) {
	fake.addRunningTaskMutex.Lock()
	defer fake.addRunningTaskMutex.Unlock()
	fake.AddRunningTaskStub = nil
	fake.addRunningTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskManager) AddRunningTaskReturnsOnCall(i int, result1 error) {
	fake.addRunningTaskMutex.Lock()
	defer fake.addRunningTaskMutex.Unlock()
	fake.AddRunningTaskStub = nil
	if fake.addRunningTaskReturnsOnCall == nil {
		fake.addRunningTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addRunningTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskManager) AddTask(arg1 string, arg2 goasync.Task) error {
	fake.addTaskMutex.Lock()
	ret, specificReturn := fake.addTaskReturnsOnCall[len(fake.addTaskArgsForCall)]
	fake.addTaskArgsForCall = append(fake.addTaskArgsForCall, struct {
		arg1 string
		arg2 goasync.Task
	}{arg1, arg2})
	stub := fake.AddTaskStub
	fakeReturns := fake.addTaskReturns
	fake.recordInvocation("AddTask", []interface{}{arg1, arg2})
	fake.addTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskManager) AddTaskCallCount() int {
	fake.addTaskMutex.RLock()
	defer fake.addTaskMutex.RUnlock()
	return len(fake.addTaskArgsForCall)
}

func (fake *FakeTaskManager) AddTaskCalls(stub func(string, goasync.Task) error) {
	fake.addTaskMutex.Lock()
	defer fake.addTaskMutex.Unlock()
	fake.AddTaskStub = stub
}

func (fake *FakeTaskManager) AddTaskArgsForCall(i int) (string, goasync.Task) {
	fake.addTaskMutex.RLock()
	defer fake.addTaskMutex.RUnlock()
	argsForCall := fake.addTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskManager) AddTaskReturns(result1 error) {
	fake.addTaskMutex.Lock()
	defer fake.addTaskMutex.Unlock()
	fake.AddTaskStub = nil
	fake.addTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskManager) AddTaskReturnsOnCall(i int, result1 error) {
	fake.addTaskMutex.Lock()
	defer fake.addTaskMutex.Unlock()
	fake.AddTaskStub = nil
	if fake.addTaskReturnsOnCall == nil {
		fake.addTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskManager) Run(arg1 context.Context) []goasync.NamedError {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskManager) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeTaskManager) RunCalls(stub func(context.Context) []goasync.NamedError) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeTaskManager) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTaskManager) RunReturns(result1 []goasync.NamedError) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 []goasync.NamedError
	}{result1}
}

func (fake *FakeTaskManager) RunReturnsOnCall(i int, result1 []goasync.NamedError) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 []goasync.NamedError
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 []goasync.NamedError
	}{result1}
}

func (fake *FakeTaskManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addRunningTaskMutex.RLock()
	defer fake.addRunningTaskMutex.RUnlock()
	fake.addTaskMutex.RLock()
	defer fake.addTaskMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ goasync.TaskManager = new(FakeTaskManager)
